# Generated by Django 4.2.7 on 2023-11-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('phoneumber', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
