# Generated by Django 4.2.7 on 2023-11-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecard',
            old_name='phoneumber',
            new_name='phonenumber',
        ),
    ]
