# Generated by Django 4.2.7 on 2023-11-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0003_alter_namecard_address_alter_namecard_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecard',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='namecard',
            old_name='company',
            new_name='C1ompany',
        ),
        migrations.RenameField(
            model_name='namecard',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='namecard',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='namecard',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
        migrations.RenameField(
            model_name='namecard',
            old_name='role',
            new_name='Role',
        ),
    ]
