# Generated by Django 4.2.7 on 2023-11-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0005_rename_c1ompany_namecard_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='media/default_image.jpg', upload_to='')),
            ],
        ),
    ]
