# Generated by Django 4.2.7 on 2023-11-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0008_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
