# Generated by Django 4.2.7 on 2023-11-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0009_alter_post_id_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
