# Generated by Django 4.2.7 on 2023-11-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0010_remove_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='file_dated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='file_path',
            field=models.FileField(blank=True, upload_to='media/images /%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
