# Generated by Django 4.2.7 on 2023-11-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0012_postimage_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='contents',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
