# Generated by Django 4.2.7 on 2023-11-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0013_postimage_contents_postimage_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='uploaded_at',
        ),
    ]
